# Generated by Django 3.0.4 on 2020-03-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Kapurthala', max_length=100)),
                ('town', models.CharField(default='anonymous', max_length=30)),
                ('village', models.CharField(max_length=100)),
                ('lastsmstimestamp', models.CharField(max_length=100)),
                ('success', models.CharField(max_length=100)),
                ('error', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('addedtimestamp', models.TextField(max_length=100)),
            ],
        ),
    ]
