# Generated by Django 3.0.4 on 2020-03-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addedtimestamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='error',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastsmstimestamp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='success',
        ),
        migrations.RemoveField(
            model_name='user',
            name='town',
        ),
        migrations.RemoveField(
            model_name='user',
            name='village',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Aman', max_length=100),
        ),
    ]
