# Generated by Django 3.0.5 on 2020-04-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200331_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='Kapurthala', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
