# Generated by Django 3.0.5 on 2020-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200404_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='failed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='success',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
