# Generated by Django 3.0.5 on 2020-04-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200404_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='failed',
            new_name='error',
        ),
    ]
