# Generated by Django 3.0.5 on 2020-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200404_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_sms',
            field=models.DateTimeField(blank=True),
        ),
    ]
